### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by jocap** [vapid/vapid#135]
**Describe the bug**
I've just installed vapid via npm, and I can't create a new project. It fails, complaining about not locating the bindings file.

**To Reproduce**
1. `sudo npm install -g vapid`
2. `vapid new x` (or actually, even just `vapid`)
3. See error

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: OpenBSD 6.4
 - Node Version: v8.12.0
 - Vapid Version: ? (latest)

**Error**

```
/usr/local/lib/node_modules/@vapid/cli/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/build/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/build/Debug/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/build/Release/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/out/Debug/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/Debug/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/out/Release/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/Release/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/build/default/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/compiled/8.12.0/openbsd/x64/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/addon-build/release/install-root/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/addon-build/debug/install-root/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/addon-build/default/install-root/sharp.node
 → /usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/lib/binding/node-v57-openbsd-x64/sharp.node
    at bindings (/usr/local/lib/node_modules/@vapid/cli/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/lib/constructor.js:10:34)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vapid/cli/node_modules/sharp/lib/index.js:3:15)
```

**Comment by srobbin** [comment]
@jocap Thanks for submitting this. Here's the command you can use to see which version of Vapid you're running:

```
vapid -v
```

**Comment by jocap** [comment]
Scott, thanks for your reply.  Again, the vapid command doesn't work;
`vapid -v` results in the same error.

**Comment by srobbin** [comment]
@jocap Maybe try forcefully re-installing/upgrading?

```
npm install -g @vapid/cli
```
