### ISSUE TITLE
Flatpickr import not working

### ISSUE THREAD

**Issue by w-biggs** [vapid/vapid#136]
**Describe the bug**
Attempting to run `vapid start .` fails and outputs the following errors:

```
ERROR in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss
Module build failed (from /usr/local/share/.config/yarn/global/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from /usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js):

@import "~flatpickr/dist/flatpickr.min";
       ^
      Can't find stylesheet to import.
   ╷
29 │ @import "~flatpickr/dist/flatpickr.min";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  stdin 29:9  root stylesheet
      in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss (line 29, column 9)
    at runLoaders (/usr/local/share/.config/yarn/global/node_modules/webpack/lib/NormalModule.js:301:20)
    at /usr/local/share/.config/yarn/global/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /usr/local/share/.config/yarn/global/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/usr/local/share/.config/yarn/global/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at render (/usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js:52:13)
    at Function.$2 (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:24382:48)
    at wO.$2 (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:15310:15)
    at uT.vr (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:9042:42)
    at uT.vq (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:9044:32)
    at iz.uD (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:8392:46)
    at us.$0 (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:8534:7)
    at Object.eG (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:1512:80)
    at ad.ba (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:8455:3)
    at iN.ba (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:8385:25)
    at iN.cv (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:8372:6)
    at py.cv (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:8162:35)
    at Object.m (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:1383:19)
    at /usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:5070:51
    at xe.a (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:1394:71)
    at xe.$2 (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:8177:23)
    at vR.$2 (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:8172:25)
    at uT.vr (/usr/local/share/.config/yarn/global/node_modules/sass/sass.dart.js:9042:42)
 @ multi /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss dashboard/stylesheets/dashboard[0]

ERROR in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/ace.js
Module not found: Error: Can't resolve 'ace-builds' in '/usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard'
 @ /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/ace.js 1:0-21
 @ /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
 @ multi /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js

ERROR in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/datepicker.js
Module not found: Error: Can't resolve 'flatpickr' in '/usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard'
 @ /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/datepicker.js 1:18-38
 @ /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
 @ multi /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js

ERROR in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
Module not found: Error: Can't resolve 'jquery' in '/usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts'
 @ /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js 1:15-32
 @ multi /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js

ERROR in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/wysiwyg.js
Module not found: Error: Can't resolve 'quill' in '/usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard'
 @ /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/wysiwyg.js 1:14-30
 @ /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
 @ multi /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js

ERROR in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
Module not found: Error: Can't resolve 'turbolinks' in '/usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts'
 @ /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js 4:19-40
 @ multi /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
Child mini-css-extract-plugin ../../../usr/local/share/.config/yarn/global/node_modules/css-loader/index.js??ref--4-1!../../../usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!../../../usr/local/share/.config/yarn/global/node_modules/resolve-url-loader/index.js!www/stylesheets/site.pack.scss:
    Entrypoint mini-css-extract-plugin = *
    [../../../css-loader/index.js?!../../../sass-loader/lib/loader.js?!../../../resolve-url-loader/index.js!../../../../../../../../../../c/Development/nautiquos/www/stylesheets/site.pack.scss] /usr/local/share/.config/yarn/global/node_modules/css-loader??ref--4-1!/usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/usr/local/share/.config/yarn/global/node_modules/resolve-url-loader!./www/stylesheets/site.pack.scss 10.1 KiB {mini-css-extract-plugin} [built] [1 warning]
    [../../../css-loader/lib/css-base.js] /usr/local/share/.config/yarn/global/node_modules/css-loader/lib/css-base.js 2.21 KiB {mini-css-extract-plugin} [built]

    WARNING in ./www/stylesheets/site.pack.scss (/usr/local/share/.config/yarn/global/node_modules/css-loader??ref--4-1!/usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/usr/local/share/.config/yarn/global/node_modules/resolve-url-loader!./www/stylesheets/site.pack.scss)
    Module Warning (from /usr/local/share/.config/yarn/global/node_modules/resolve-url-loader/index.js):
    (Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
      /c/Development/nautiquos/www/stylesheets/site.pack.scss:27:3: missing '}'
      at error (/usr/local/share/.config/yarn/global/node_modules/css/lib/parse/index.js:62:15)
Child mini-css-extract-plugin ../../../usr/local/share/.config/yarn/global/node_modules/css-loader/index.js??ref--4-1!../../../usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!../../../usr/local/share/.config/yarn/global/node_modules/resolve-url-loader/index.js!../../../usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss:
    Entrypoint mini-css-extract-plugin = *
    [../../../css-loader/index.js?!../../../sass-loader/lib/loader.js?!../../../resolve-url-loader/index.js!../assets/dashboard/stylesheets/dashboard.pack.scss] /usr/local/share/.config/yarn/global/node_modules/css-loader??ref--4-1!/usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/usr/local/share/.config/yarn/global/node_modules/resolve-url-loader!/usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss 497 bytes {mini-css-extract-plugin} [built] [failed] [1 warning] [1 error]

    WARNING in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss (/usr/local/share/.config/yarn/global/node_modules/css-loader??ref--4-1!/usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/usr/local/share/.config/yarn/global/node_modules/resolve-url-loader!/usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss)
    Module Warning (from /usr/local/share/.config/yarn/global/node_modules/resolve-url-loader/index.js):
    (Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
      /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss:29:41: missing '{'
      at error (/usr/local/share/.config/yarn/global/node_modules/css/lib/parse/index.js:62:15)

    ERROR in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss (/usr/local/share/.config/yarn/global/node_modules/css-loader??ref--4-1!/usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/usr/local/share/.config/yarn/global/node_modules/resolve-url-loader!/usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss)
    Module build failed (from /usr/local/share/.config/yarn/global/node_modules/sass-loader/lib/loader.js):

    @import "~flatpickr/dist/flatpickr.min";
           ^
          Can't find stylesheet to import.
       ╷
    29 │ @import "~flatpickr/dist/flatpickr.min";
       │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       ╵
      stdin 29:9  root stylesheet
          in /usr/local/share/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss (line 29, column 9)
```

**To Reproduce**
1. `vapid new test`
2. `vapid start test`

**Expected behavior**
It should be running normally...

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: `Ubuntu 18.04.1 LTS` on Windows Subsystem for Linux
 - Node Version [e.g. 8.11.1]: `v11.12.0`
 - Vapid Version [e.g. 0.1.24, found in package.json]: `Vapid 0.8.0`

**Additional context**
Probably due to the tilde import, but I'm not sure why that's causing this issue - it seems like Vapid's dependencies are all the correct version. I've tried uninstalling Vapid, clearing yarn's cache, and re-installing Vapid, but it still doesn't work.

**Comment by srobbin** [comment]
@w-biggs Yikes, looks like it's having trouble finding a bunch of the modules (ace-builds, jquery, quill, turbolinks, etc.) Maybe try uninstalling then reinstalling?

```
npm uninstall -g @vapid/cli
npm install -g @vapid/cli
```

**Comment by w-biggs** [comment]
I tried that (with yarn at least) and it didn't fix the issue. I tried to do it with npm but I had issues with pre-node-gyp due to node/npm being installed as root, so I tried to install it without root but nvm doesn't work on my shell (fish), and I haven't had time yet to install bass in order to install nvm in order to install node/npm without root in order to try installing vapid with npm yet. Lol.

I'll let you know tomorrow if that gets it working.

**Comment by w-biggs** [comment]
I got `nvm` working and installed `node`/`npm` without root. I then re-installed `yarn` and tried to install `vapid` with it, but it had the same issues. I then retried installing `vapid` using `npm`, and it now works properly. Phew. Not sure why it has such major issues with `yarn` but this works at least.

**Comment by w-biggs** [comment]
I guess changing this to a "vapid doesn't work with yarn" issue would make the most sense, since that's still a problem, albeit one with a workaround.

**Comment by srobbin** [comment]
@w-biggs Ah yeah, I get the same error with `yarn global`. Weird.
