### ISSUE TITLE
Dashboard CSS doesn't compile 

### ISSUE THREAD

**Issue by tzekid** [vapid/vapid#145]
**What**
The dashboard doesn't have any stylesheets and the console gives a lot of errors.

**Reproduce**
1.) Install the cli app via NPM
2.) Create a new project and run vapid
3.) Open the dashboard

**Screenshots**
![Screenshot_20190605_144512](https://user-images.githubusercontent.com/6037154/58957299-a25c8400-87a0-11e9-867e-db21348071e9.png)

**Your Environment**
Include relevant details, so others can replicate the issue.
 - OS: Manjaro Linux
 - Browser: Chrome
 - Node Version: v11.15.0
 - Vapid Version: Vapid 0.8.3

**Console Output**
```bash
...
ERROR in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss
Module build failed (from /home/kid/.config/yarn/global/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from /home/kid/.config/yarn/global/node_modules/sass-loader/lib/loader.js):

@import "~flatpickr/dist/flatpickr.min";
       ^
      Can't find stylesheet to import.
   ╷
29 │ @import "~flatpickr/dist/flatpickr.min";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  stdin 29:9  root stylesheet
      in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss (line 29, column 9)
    at runLoaders (/home/kid/.config/yarn/global/node_modules/webpack/lib/NormalModule.js:302:20)
    at /home/kid/.config/yarn/global/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/kid/.config/yarn/global/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/kid/.config/yarn/global/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at render (/home/kid/.config/yarn/global/node_modules/sass-loader/lib/loader.js:52:13)
    at Function.$2 (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:23927:48)
    at xS.$2 (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:14932:15)
    at vX.wa (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8897:42)
    at vX.w9 (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8899:32)
    at iM.vm (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8296:46)
    at vj.$0 (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8432:7)
    at Object.eP (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:1465:80)
    at ak.bc (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8354:3)
    at j_.bc (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8291:25)
    at j_.cA (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8278:6)
    at pL.cA (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8080:35)
    at Object.m (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:1348:19)
    at /home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:4974:51
    at yi.a (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:1356:71)
    at yi.$2 (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8095:23)
    at wU.$2 (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8090:25)
    at vX.wa (/home/kid/.config/yarn/global/node_modules/sass/sass.dart.js:8897:42)
 @ multi /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss dashboard/stylesheets/dashboard[0]

ERROR in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/ace.js
Module not found: Error: Can't resolve 'ace-builds' in '/home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard'
 @ /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/ace.js 1:0-21
 @ /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
 @ multi /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js

ERROR in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/datepicker.js
Module not found: Error: Can't resolve 'flatpickr' in '/home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard'
 @ /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/datepicker.js 1:18-38
 @ /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
 @ multi /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js

ERROR in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
Module not found: Error: Can't resolve 'jquery' in '/home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts'
 @ /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js 1:15-32
 @ multi /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js

ERROR in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/wysiwyg.js
Module not found: Error: Can't resolve 'quill' in '/home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard'
 @ /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard/wysiwyg.js 1:14-30
 @ /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
 @ multi /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js

ERROR in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
Module not found: Error: Can't resolve 'turbolinks' in '/home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts'
 @ /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js 4:19-40
 @ multi /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/javascripts/dashboard.pack.js
Child mini-css-extract-plugin ../../.config/yarn/global/node_modules/css-loader/index.js??ref--4-1!../../.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!../../.config/yarn/global/node_modules/resolve-url-loader/index.js!../../.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss:
    Entrypoint mini-css-extract-plugin = *
    [../../../css-loader/index.js?!../../../sass-loader/lib/loader.js?!../../../resolve-url-loader/index.js!../assets/dashboard/stylesheets/dashboard.pack.scss] /home/kid/.config/yarn/global/node_modules/css-loader??ref--4-1!/home/kid/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/home/kid/.config/yarn/global/node_modules/resolve-url-loader!/home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss 483 bytes {mini-css-extract-plugin} [built] [failed] [1 warning] [1 error]

    WARNING in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss (/home/kid/.config/yarn/global/node_modules/css-loader??ref--4-1!/home/kid/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/home/kid/.config/yarn/global/node_modules/resolve-url-loader!/home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss)
    Module Warning (from /home/kid/.config/yarn/global/node_modules/resolve-url-loader/index.js):
    (Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
      /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss:29:41: missing '{'
      at error (/home/kid/.config/yarn/global/node_modules/css/lib/parse/index.js:62:15)

    ERROR in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss (/home/kid/.config/yarn/global/node_modules/css-loader??ref--4-1!/home/kid/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/home/kid/.config/yarn/global/node_modules/resolve-url-loader!/home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss)
    Module build failed (from /home/kid/.config/yarn/global/node_modules/sass-loader/lib/loader.js):

    @import "~flatpickr/dist/flatpickr.min";
           ^
          Can't find stylesheet to import.
       ╷
    29 │ @import "~flatpickr/dist/flatpickr.min";
       │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       ╵
      stdin 29:9  root stylesheet
          in /home/kid/.config/yarn/global/node_modules/@vapid/cli/assets/dashboard/stylesheets/dashboard.pack.scss (line 29, column 9)
Child mini-css-extract-plugin ../../.config/yarn/global/node_modules/css-loader/index.js??ref--4-1!../../.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!../../.config/yarn/global/node_modules/resolve-url-loader/index.js!www/stylesheets/site.pack.scss:
    Entrypoint mini-css-extract-plugin = *
    [../../../css-loader/index.js?!../../../sass-loader/lib/loader.js?!../../../resolve-url-loader/index.js!../../../../../../../Projects/blasorchesterhoechst/www/stylesheets/site.pack.scss] /home/kid/.config/yarn/global/node_modules/css-loader??ref--4-1!/home/kid/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/home/kid/.config/yarn/global/node_modules/resolve-url-loader!./www/stylesheets/site.pack.scss 10.1 KiB {mini-css-extract-plugin} [built] [1 warning]
    [../../../css-loader/lib/css-base.js] /home/kid/.config/yarn/global/node_modules/css-loader/lib/css-base.js 2.21 KiB {mini-css-extract-plugin} [built]

    WARNING in ./www/stylesheets/site.pack.scss (/home/kid/.config/yarn/global/node_modules/css-loader??ref--4-1!/home/kid/.config/yarn/global/node_modules/sass-loader/lib/loader.js??ref--4-2!/home/kid/.config/yarn/global/node_modules/resolve-url-loader!./www/stylesheets/site.pack.scss)
    Module Warning (from /home/kid/.config/yarn/global/node_modules/resolve-url-loader/index.js):
    (Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: CSS error
      /home/kid/Projects/blasorchesterhoechst/www/stylesheets/site.pack.scss:27:3: missing '}'
      at error (/home/kid/.config/yarn/global/node_modules/css/lib/parse/index.js:62:15)
GET / 200 6492 - 82.589 ms [-]
GET / 200 6492 - 66.291 ms [-]
GET /dashboard/sections/1/records/new 200 6589 - 87.517 ms [-]
GET /dashboard/stylesheets/dashboard.css 404 1811 - 8.969 ms [-]
...
```

**Comment by srobbin** [comment]
@tzekid Thanks for reporting this. We've got a similar issued opened in #136 (so I'm going to close this one). It appears to be an issue with a yarn global install. The quick workaround is to install via npm:

`npm install -g @vapid/cli`

Hopefully, we'll figure out the issue with yarn soon.
