### ISSUE TITLE
Response code 500 vapid deploy

### ISSUE THREAD

**Issue by KeizerDev** [vapid/vapid#169]
Hi,

I am getting a 500 Error when trying to deploy vapid. I think it has something to do with my credentials but I can't find the config file where this is stored. 
```
$ vapid deploy  
? Is this a new website? Yes
? Would you like to deploy the existing content too? Yes
(node:75853) UnhandledPromiseRejectionWarning: HTTPError: Response code 500 (Internal Server Error)
    at /usr/local/lib/node_modules/@vapid/cli/node_modules/got/index.js:386:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:75853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:75853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks in advance

**Comment by srobbin** [comment]
@KeizerDev I'm so sorry to hear that. Can you please email me at hello@vapid.com? I can help troubleshoot there.
