### ISSUE TITLE
Error when installing vapid-cli

### ISSUE THREAD

**Issue by tobiasger** [vapid/vapid#20]
I get this error when trying to install vapid-cli through npm:

```
> bcrypt@2.0.1 install /usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Pre-built binaries not installable for bcrypt@2.0.1 and node@10.10.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/lib'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/tobiasgerhardsson/.node-gyp/10.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/.node-gyp'
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/local/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Any idea why this is happening?

**Comment by tobiasger** [comment]
Adding the `--unsafe-perm` fixed it. Like this: `sudo npm install --unsafe-perm vapid-cli -g`.

Maybe this isn't a problem with vapid-cli per se.

**Comment by kevinruby** [comment]
On OSX I fixed it with the following cmds:

`sudo chown -R yourname ~/.npm`
`sudo chown -R yourname /usr/local/lib/node_modules`

This error isn't a related problem with vapid-cli.

**Comment by dthreatt** [comment]
Mine installed but I cant run  

![2018-09-27 13_26_10-vapid - cloud9](https://user-images.githubusercontent.com/8387791/46172973-d7035d80-c259-11e8-8f37-be307cc979fc.png)

**Comment by srobbin** [comment]
@dthreatt Looks like you may be using a version of Node < 8.9.

I'm going to close this thread, and ask anyone else who needs install help to use [Vapid's forums](https://forums.vapid.com/). We're going to try to keep GitHub issues focused on software development, and encourage install, hosting, and general usage questions to use the forums.

**Comment by makitsune** [comment]
I just had this same problem using Node v12.16.1
`npm i -g --unsafe-perm @vapid/cli` worked for me
