### ISSUE TITLE
sqlite3 must be installed manually

### ISSUE THREAD

**Issue by luanpiegas** [vapid/vapid#30]
```
$ vapid start vapid2
ERROR: Please install sqlite3 package manually
```

**Comment by luanpiegas** [comment]
Fixed doind this:

https://github.com/zeit/pkg/issues/264#issuecomment-338148771

**Comment by ddamato** [comment]
Yep, have the same problem. I grabbed the node_sqlite3.node file and moved it into a few directories in my project while trying to start the server. None of it worked. More specific steps for this project would be beneficial.

**Comment by ddamato** [comment]
Ok I got it, has nothing to do with the binary. All you need is `npm install` and then `npm start`.

**Comment by clarklab** [comment]
Running npm install gets me a big giant error:

```> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Pre-built binaries not installable for bcrypt@2.0.1 and node@10.4.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Hit error EACCES: permission denied, mkdir '/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/lib'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/build'
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/spacebeast/Source/vapid/cover/node_modules/bcrypt
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/spacebeast/Source/vapid/cover/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/spacebeast/Source/vapid/cover/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN cover@ No description
npm WARN cover@ No repository field.
npm WARN cover@ No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:```

**Comment by srobbin** [comment]
@clarklab Looks like that might be a different error than the SQLite one being discussed here. In any case, this article may end up to help you resolve both:

https://windowswebdev.io/getting-vapid-up-and-running-on-wsl-ubuntu
