### ISSUE TITLE
Vapid Unexpected Token cli.js:13

### ISSUE THREAD

**Issue by styledev** [vapid/vapid#40]
After installing with sudo any time I try to use `vapid new {path}` or just `vapid` by itself I get the following error:

`$ vapid
/usr/local/lib/node_modules/vapid-cli/bin/cli.js:14
  return async (target) => {
               ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)`

**Comment by angelawolak** [comment]
Hi, I had the same error and updating my node.js fixed the issue.

**Comment by srobbin** [comment]
@styledev Looks like you're running an earlier version of Node. You can type `node -v` to see which version.

In any case, I'd recommend upgrading to the latest (v8.12 is fine):
https://nodejs.org/en/

Let me know how it goes.
