### ISSUE TITLE
unexpected token error when running new

### ISSUE THREAD

**Issue by dking3876** [vapid/vapid#45]
after installing i can't start a new project.

get the following 

`C:\users\AppData\Roaming\npm\node_modules\vapid-cli\bin\cli.js:13
return async (target) => {

SyntaxError: Unexpected token (
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:483:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:392:7)
at startup (bootstrap_node.js:150:9)
`

Im running node v6.10.1
and npm 5.6.0

**Comment by HueyGeek** [comment]
Same issue but at node v6.14.4, npm  v3.10.10, over linux 4.15.0-34-generic #37~16.04.1-Ubuntu SMP x64

/usr/local/lib/node_modules/vapid-cli/bin/cli.js:13
  return async (target) => {
               ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by srobbin** [comment]
Vapid [requires Node v8.9.0 or higher](https://github.com/vapid/vapid/blob/master/package.json#L16). Sorry, I should have put that in the README—just added it now.

I'm going to close this issue. If you have any follow-up installation questions, please chime in on Issue #20.

**Comment by dthreatt** [comment]
yes in order to do that just do

nvm i 8.9.0

after i did that everything worked fine.

I think on your SETUP you need to say you need Node v8.9.0 or higher on the install screen
