### ISSUE TITLE
Cannot exit when port in use

### ISSUE THREAD

**Issue by thgh** [vapid/vapid#5]
I couldn't close the program with Ctrl+C

Possible solution: https://github.com/Rich-Harris/port-authority

```
==> Starting the development server...
==> Watching for changes in /.../www
View your website at http://localhost:3000
Ctrl + C to quit
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Server.listen (livereload/lib/livereload.js:80:28)
    at Object.exports.createServer (livereload/lib/livereload.js:246:14)
    at Watcher.listen (vapid-cli/lib/watcher.js:35:22)
    at Vapid.start (vapid-cli/lib/vapid.js:150:20)
    at <anonymous>
Emitted 'error' event at:
    at Server.onError (livereload/lib/livereload.js:99:19)
    at WebSocketServer.emit (events.js:180:13)
    at Server.WebSocketServer._onServerError (livereload/node_modules/ws/lib/WebSocketServer.js:82:50)
    at Server.emit (events.js:180:13)
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by srobbin** [comment]
@thgh Great submission, and thanks for the link to port-authority. I'll submit a PR for this one soon.

**Comment by srobbin** [comment]
@thgh Just create a pull request to fix this bug. Let me know if you're able to test/verify.
