### ISSUE TITLE
Permission denied even with sudo rights (ubuntu)

### ISSUE THREAD

**Issue by hajek-raven** [vapid/vapid#63]
**Describe the bug**
When I install vapid-cli with sudo rights, bcrypt throws access error even if the folder is set to chmod 777.
`sudo npm install -g vapid-cli`

**Log**
```
node-pre-gyp ERR! Pre-built binaries not installable for bcrypt@2.0.1 and node@8.12.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error EACCES: permission denied, mkdir '/usr/lib/node_modules/vapid-cli/node_modules/bcrypt/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/vapid-cli/node_modules/bcrypt/build'
gyp ERR! System Linux 4.15.0-36-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/usr/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /usr/lib/node_modules/vapid-cli/node_modules/bcrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/usr/lib/node_modules/vapid-cli/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/vapid-cli/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.15.0-36-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/vapid-cli/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/vapid-cli/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
```

**Expected behavior**
Install vapid-cli correctly.

**Environment**
Include relevant details, so others can replicate the issue.
 - OS: [Ubuntu 18.04]
 - Node Version [8.12.0]

**Comment by hajek-raven** [comment]
As I dig into this issue it can be fixed by installing it like this:
`sudo npm install --unsafe-perm vapid-cli -g`

I think that this is not a problem with vapid but with npm or bcrypt package.
